on:
  workflow_dispatch:
  push:
    branches:
      - main

name: Prerelease

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        include:
          - os: macos-latest
            output: starhopper.bin
            extras: >-
              --macos-create-app-bundle
          - os: ubuntu-latest
            output: starhopper.bin
            extras:
          - os: windows-latest
            output: starhopper.exe
            extras:

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.11"

      - name: Install patchelf on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y patchelf

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Build nuitka binaries
        if: matrix.os == 'macos-latest'
        run: >
          poetry run nuitka3
          --onefile
          --disable-console
          --output-dir=builds
          -o=starhopper.app 
          --macos-create-app-bundle
          --enable-plugins=pyside6
          starhopper/gui/app.py

      - name: Build nuitka binaries
        if: matrix.os == 'ubuntu-latest'
        run: >
          poetry run nuitka3
          --onefile
          --disable-console
          --output-dir=builds
          -o=starhopper.bin
          --enable-plugins=pyside6
          starhopper/gui/app.py

      - name: Build nuitka binaries
        if: matrix.os == 'windows-latest'
        run: >
          poetry run nuitka3
          --onefile
          --disable-console
          --output-dir=builds
          -o=starhopper.exe
          --enable-plugins=pyside6
          starhopper/gui/app.py

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        if : matrix.os == 'macos-latest'
        with:
          name: starhopper
          path: builds/starhopper.app

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        if : matrix.os == 'ubuntu-latest'
        with:
          name: starhopper
          path: builds/starhopper.bin

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        if : matrix.os == 'windows-latest'
        with:
          name: starhopper
          path: builds/starhopper.exe

