on:
  workflow_dispatch:
  push:
    branches:
      - main

name: Prerelease

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        include:
          - os: macos-latest
            output: starhopper.bin
          - os: ubuntu-latest
            output: starhopper.bin
            extras:
          - os: windows-latest
            output: starhopper.exe
            extras:

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.11"

      - name: Install patchelf on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y patchelf

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Build nuitka binaries
        if: matrix.os == 'macos-latest'
        run: >-
          poetry run nuitka3
          --onefile
          --disable-console
          --output-dir=builds
          -o starhopper.osx.bin 
          --macos-create-app-bundle
          --enable-plugins=pyside6
          starhopper/gui/app.py

      - name: Build nuitka binaries
        if: matrix.os == 'ubuntu-latest'
        run: >-
          poetry run nuitka3
          --onefile
          --disable-console
          --output-dir=builds
          -o starhopper.bin
          --enable-plugins=pyside6
          starhopper/gui/app.py

      - name: Build nuitka binaries
        if: matrix.os == 'windows-latest'
        run: >-
          poetry run nuitka
          --onefile
          --disable-console
          --output-dir=builds
          -o starhopper.exe
          --enable-plugins=pyside6
          --assume-yes-for-downloads
          starhopper/gui/app.py

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: starhopper
          path: |
            builds/starhopper.bin
            builds/starhopper.osx.bin
            builds/starhopper.exe
            

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: starhopper
          path: builds

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"

      - name: Creating prerelease
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            builds/*
          prerelease: true
          body: |
            This is a prerelease of StarHopper.
            It is not intended for production use.