on:
  workflow_dispatch:
  release:
    types:
      - published

name: Release

jobs:
  sdist:
    name: Creating source release

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.0.0

    - name: Set up Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: "3.11"

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Setup Poetry
      run: poetry config pypi-token.pypi "${{ secrets.PYPI_TOKEN }}"

    - name: Publish package
      run: poetry publish --build